name: Build tomcat

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out tomcat-users.xml
        uses: actions/checkout@v4

      - name: List project files and java version
        run: |
          ls -ltr
          java -version

      - name: Check out Apache Tomcat
        uses: actions/checkout@v4
        with:
          repository: apache/tomcat
          ref: main
          path: ./tomcat

      - name: Set up Java 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
          java-package: jdk
          architecture: x64

      - name: List project files and version
        run: |
          ls -ltr
          java -version

      - name: Copy tomcat-users.xml into Tomcat configuration directory
        run: cp -v tomcat-users.xml ./tomcat/conf/tomcat-users.xml

      - name: Compile tomcat
        run: |
          cd ./tomcat
          ant


